### ISSUE TITLE
Mail smtp

### ISSUE THREAD

**Issue by matodrobec** [nette/tracy#262]
- version: 2.4.9

### Description

how to setup smtp. Is it possible setup smtp? I try to set up it like here https://forum.nette.org/en/27799-integration-between-tracy-and-nette-imailer but it is not working

```yaml
services:
    tracyMailer:
        class: App\CoreModule\Mail\Tracy\Mailer(Nette\Mail\IMailer, '%tracy.fromEmail%')

    tracy.logger:
        factory: Tracy\Debugger::getLogger()
        setup:
            - $mailer([@tracyMailer, 'send'])
```
