### ISSUE TITLE
Tracy debug bar has no styling due to `all: revert`

### ISSUE THREAD

**Issue by NoNoNo** [nette/tracy#394]
https://github.com/nette/tracy/commit/f67ad80479ad06ec2fa124a3afb507235b16a875 introduced `#tracy-debug :not(svg):not(img):not(table) { all: revert; }` to `src/Tracy/Bar/assets/bar.css`.

This overrides all styling of the Tracy debug bar due to higher precedence / specificity:

```CSS
#tracy-debug :not(svg):not(img):not(table) {
  width: initial;
  height: initial;
  all: revert;
}

#tracy-debug-bar {
  ~~font: normal normal 13px/1.55 Tahoma, sans-serif;~~
  ~~color: #333;~~
  ~~border: 1px solid #c9c9c9;~~
  ~~background: #EDEAE0 url('data:image/png;base64,R0lG…Ds=') top;~~
  ~~background-size: 1em;~~
  ~~position: fixed;~~
  ~~min-width: 50px;~~
  ~~white-space: nowrap;~~
  ~~z-index: 30000;~~
  ~~opacity: .9;~~
  ~~transition: opacity 0.2s;~~
  ~~will-change: opacity, top, left;~~
  ~~border-radius: 3px;~~
  ~~box-shadow: 1px 1px 10px rgba(0, 0, 0, .15);~~
}
```

Please test with a browser that understands `all: revert` cfg. https://caniuse.com/css-all && https://caniuse.com/css-revert-value (only FF and Safari at the moment! Chrome, IE and Edge do not).
