### ISSUE TITLE
prevent hidden character hints in dumps from being copied

### ISSUE THREAD

**Issue by BernhardBaumrock** [nette/tracy#458]
- Is your feature request related to a problem? Please describe.

Yes, see here: https://processwire.com/talk/topic/24979-n-in-string-dumps/?do=findComment&comment=210305

- Explain your intentions.

```css
.tracy-dump-string i {
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```

I don't know if that css selector works only in the ProcessWire module or also for tracy core, but that hack prevents copying \n characters. Not sure if there are any other dump infos that you are wrapping in <i> tags in the dump that should stay in the copied output?

- It's up to you to make a strong case to convince the project's developers of the merits of this feature.

Well, as mentioned in the linked thread it was so simple to dump a nicely formatted SQL statement to the console/bar and then just copy/paste that to my local mysql client. Now I either have to remove all \n from the copied string or dump it using `echo("<pre>...</pre>")`. That's a huge step back.

Thx for considering :)
