### ISSUE TITLE
Expand arrow position broken in Firefox

### ISSUE THREAD

**Issue by Gappa** [nette/tracy#460]
Version: 2.8.2

### Bug Description

The expand arrow position is broken in Firefox, it is OK in Chrome.

![tracy](https://user-images.githubusercontent.com/749981/105704635-63e48180-5f0f-11eb-842b-60677895002c.png)

### Steps To Reproduce

Open a tracy panel that has something to expand, e.g. the new Latte Templates panel.

### Expected Behavior

Arrow is vertically centered and at the end of the line.

### Possible Solution

Adding this to the existing CSS seems to fix it:

``` css
#tracy-debug .tracy-toggle:after {
	...
	line-height: 0;
}
```
